export const SET_LOGIN = 'SET_LOGIN'
export const SET_LOGIN_ERROR = 'SET_LOGIN_ERROR'
export const SET_LOADINGS_LOGIN = 'SET_LOADINGS_LOGIN'
export const DISMISS_LOADING_LOGIN = 'DISMISS_LOADING_LOGIN'